version: '1'

services:
  app:
    image: 'drone-app:latest'
    ports:
      - "8089:8089"

    build:
      context: .
    container_name: app
    depends_on:
      - drone
    environment:
      - DB_USERNAME=aaron
      - DB_PASSWORD=aaron
      - DB_URL=jdbc:postgresql://drone:5432/drone_db

  drone:
    image: 'postgres:alpine'

    environment:
      - POSTGRES_USER=aaron
      - POSTGRES_PASSWORD=aaron
      - POSTGRES_DB=drone_db