server:
  port: 8089

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: musala
#    password: musala
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#  flyway:
#    url: jdbc:h2:mem:mydb
#    user: musala
#    password: musala
#    locations: classpath:db/migration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drone
    username: aaron
    password: aaron
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/drone
    user: aaron
    password: aaron
    locations: classpath:db/migration
