server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: musala
    password: musala
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    url: jdbc:h2:mem:mydb
    user: musala
    password: musala
    locations: classpath:db/migration
