server:
  port: 8089

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
#    username: musala
#    password: musala
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#  flyway:
#    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
#    baseline-on-migrate: true
#    user: musala
#    password: musala
#    locations: classpath:db/migration

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
